### ISSUE TITLE
Some more ideas

### ISSUE THREAD

**Issue by Reasno** [mudkipme/mediawiki-webhooks#1]
Nice extension.

I was thinking about the same thing several days ago but got my hands tied on other projects. I like the general idea. For our use cases though, I want to take it further and add web hook registration/mangement through native mediawiki api. Such features would require a patch to database.

**Comment by mudkipme** [comment]
Great idea. I'm thinking about hook registration/management too but I haven't come into a practicable design.

Currently I wrote a basic hook task runner in [a separate project](https://github.com/mudkipme/klinklang#wikihooks). It allows add multiple triggers and tasks in its configuration file. However the only available task now is a [hook](https://github.com/mudkipme/klinklang/blob/master/app/tasks/scss.js) to convert SCSS from certain page to CSS and write `Common.css`.

**Comment by Reasno** [comment]
That is an interesting use case. Common.css can become a mess very quickly so I imagine SCSS can be handy. 

Another use case I would like to take advantage of webhook is to sync some templates across multiple wikis. Native php solutions are often more problematic than helpful so a bot invocation does the job better.
